# Uncomment the next line to define a global platform for your project

platform :ios, '12.0'
target 'opsddddddd' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking'
  pod 'CYLTabBarController'



end
post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'x86_64' #模拟器使用x86_64,M1电脑就可以用模拟器了
end
end
end
